### ISSUE TITLE
Display VulnerabilityReports of the current revision of the selected Deployment

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard-lens-extension#26]
The Starboard Operator associates VulnerabilityReports with ReplicaSets controlled by the corresponding Deployment.
Currently the extension displays only VulnerabilityReports owned by the selected workload. However, we could lookup an active ReplicaSet and display it in the Deployment details.

**Comment by simar7** [comment]
I had a quick look at it while I was working on another issue - where is the logic that defines a pane to be visible within a info panel or not. For instance:

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/1254783/100298915-2ed7a500-2f47-11eb-8ea0-3ed76f57163c.png">


This is under `Workloads -> Deployments -> VulnerabilityReports` now I'm assuming there's some logic that "enables" VulnerabilityReport info to be show here. Is that correct?

Another example would be through this path: `Workloads -> Pods -> ReplicaSet -> VulnerabilityReports` as shown below:

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/1254783/100299015-778f5e00-2f47-11eb-90cf-236ab60f561d.png">

**Comment by danielpacak** [comment]
> I had a quick look at it while I was working on another issue - where is the logic that defines a pane to be visible within a info panel or not. For instance:
> 
> <img alt="image" width="1380" src="https://user-images.githubusercontent.com/1254783/100298915-2ed7a500-2f47-11eb-8ea0-3ed76f57163c.png">
> 
> This is under `Workloads -> Deployments -> VulnerabilityReports` now I'm assuming there's some logic that "enables" VulnerabilityReport info to be show here. Is that correct?
> 
> Another example would be through this path: `Workloads -> Pods -> ReplicaSet -> VulnerabilityReports` as shown below:
> 
> <img alt="image" width="1379" src="https://user-images.githubusercontent.com/1254783/100299015-778f5e00-2f47-11eb-90cf-236ab60f561d.png">

We define those additional sections for each workload kind (Pod, Deployment, ReplicaSet, etc.) when we register extension's capabilities in https://github.com/aquasecurity/starboard-lens-extension/blob/main/renderer.tsx#L112. For example, here's how we add **ConfigAuditReport** and **VulnerabilityReports** sections to the Deployment details pane:

```tsx
kubeObjectDetailItems = [
    {
        kind: "Deployment",
        apiVersions: ["apps/v1"],
        priority: 9,
        components: {
            Details: (props: Component.KubeObjectDetailsProps) =>
                <React.Fragment>
                    <WorkloadConfigAudit {...props} />
                    <WorkloadVulnerabilities {...props}/>
                </React.Fragment>
        }
    }
]
```

**Comment by danielpacak** [comment]
I'm closing it as stale issue.
