### ISSUE TITLE
Pack and release extension tarball to GitHub releases and/or npm registry

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard-lens-extension#28]
Lens will allows users to install extensions from tarballs or by specifying the URL. In order to support this install mode we have to pack and release the Starboard extension.

![image](https://user-images.githubusercontent.com/1322923/100337164-57a77b00-2fd7-11eb-939e-2e342ead5b1f.png)

Ideally we should perform each release on GitHub Actions runner whenever we create an annotated Git tag.

**Comment by danielpacak** [comment]
https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-nodejs-packages

**Comment by simar7** [comment]
I wonder if Lens extension is going to support installing directly from node registries one day. That would be quite cool.

**Comment by danielpacak** [comment]
> I wonder if Lens extension is going to support installing directly from node registries one day. That would be quite cool.

Not sure if that would be node registry, but the idea is to have some kind of extensions catalog so end users could search and install what they want.

**Comment by danielpacak** [comment]
Done https://github.com/aquasecurity/starboard-lens-extension/releases/tag/v0.0.1-alpha.1
