### ISSUE TITLE
Endless loading on list views if starboard K8s resources not installed

### ISSUE THREAD

**Issue by msa0311** [aquasecurity/starboard-lens-extension#47]
When testing the extension with Lens 4.1.0-alpha.1 release I've figured out that the list views are loading endless in case the starboard k8s resources are not yet installed. 

![Bildschirmfoto 2021-02-01 um 09 51 03](https://user-images.githubusercontent.com/26629812/106435357-128a4400-6473-11eb-99c7-8e0628854f18.png)

OS: Mac OS 10.14.6 (Mojave)

**Comment by aleksfront** [comment]
This is the issue within Lens itself - it doesn't inform user about loading problems. I've created a ticket for that https://github.com/lensapp/lens/issues/2060

There might be some workarounds to be done.

1. Make a test call in `componentDidMount()`, check if it fails and show error message. There is pitfall of calling kube api twice for showing vulnerability reports.
2. Make a component that listens for spinner availability and triggers error message if spinner visible for a long time.

So there're ways to avoid such behavior before https://github.com/lensapp/lens/issues/2060 will be implemented but I sugges to customize error after the fix.

**Comment by danielpacak** [comment]
I believe it's been resolved in Lens already. Please reopen if the problem persists.
