### ISSUE TITLE
App crash - ConfigAuditReports 

### ISSUE THREAD

**Issue by mathieudebrito** [aquasecurity/starboard-lens-extension#51]
Hi guys !

When I try to see the config audit reports, I get this :
> App crash at http://1585f8d9-a6de-4999-88b3-ed350c4cb30d.localhost:64917/extension/aquasecurity--starboard-lens-extension/configauditreports?lens-kube-details=%2Fapis%2Faquasecurity.github.io%2Fv1alpha1%2Fnamespaces%2Fdefault%2Fconfigauditreports%2Fdeployment-my-deployment

> Component stack:
    at s (/Users/<me>/.k8slens/extensions/aquasecurity--starboard-lens-extension/dist/renderer.js:17:3563)
    at div
    at i (/Users/<me>/.k8slens/extensions/aquasecurity--starboard-lens-extension/dist/renderer.js:1:5155)
    at Details
    at div
    at div
    at div
    at Bp (http://1585f8d9-a6de-4999-88b3-ed350c4cb30d.localhost:64917/build/Lens.js:2:7730252)
    at Qd (http://1585f8d9-a6de-4999-88b3-ed350c4cb30d.localhost:64917/build/Lens.js:2:7755712)
    at sy (http://1585f8d9-a6de-4999-88b3-ed350c4cb30d.localhost:64917/build/Lens.js:2:7876672)
    at pa (http://1585f8d9-a6de-4999-88b3-ed350c4cb30d.localhost:64917/build/Lens.js:2:7562375)
    at t (http://1585f8d9-a6de-4999-88b3-ed350c4cb30d.localhost:64917/build/Lens.js:2:193296)
    at eT (http://1585f8d9-a6de-4999-88b3-ed350c4cb30d.localhost:64917/build/Lens.js:2:8264227)
    
>Error stack:
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at s.render (/Users/<me>/.k8slens/extensions/aquasecurity--starboard-lens-extension/dist/renderer.js:17:3763)
    at _s (http://1585f8d9-a6de-4999-88b3-ed350c4cb30d.localhost:64917/build/Lens.js:2:4545334)
    at Os (http://1585f8d9-a6de-4999-88b3-ed350c4cb30d.localhost:64917/build/Lens.js:2:4545133)
    at zo (http://1585f8d9-a6de-4999-88b3-ed350c4cb30d.localhost:64917/build/Lens.js:2:4586275)
    at Cc (http://1585f8d9-a6de-4999-88b3-ed350c4cb30d.localhost:64917/build/Lens.js:2:4572231)
    at wc (http://1585f8d9-a6de-4999-88b3-ed350c4cb30d.localhost:64917/build/Lens.js:2:4572159)
    at yc (http://1585f8d9-a6de-4999-88b3-ed350c4cb30d.localhost:64917/build/Lens.js:2:4572022)
    at hc (http://1585f8d9-a6de-4999-88b3-ed350c4cb30d.localhost:64917/build/Lens.js:2:4569009)
    at http://1585f8d9-a6de-4999-88b3-ed350c4cb30d.localhost:64917/build/Lens.js:2:4518678

Please tell me if you need anything more ! 

![screenshot](https://user-images.githubusercontent.com/1231274/111549138-fd941680-877b-11eb-8e80-e3b6618c7061.png)

In the logs, I can quickly see things like this : 
> I0317 23:02:29.566448       1 request.go:621] Throttling request took 1.027018703s, request: GET:https://10.32.0.1:443/apis/admissionregistration.k8s.io/v1beta1?timeout=32s
{
  "PolarisOutputVersion": "1.0",
  "AuditTime": "2021-03-17T23:02:28Z",
  "SourceType": "Workload",
  "SourceName": "default/Deployment.apps/v1/<>",
  "DisplayName": "default/Deployment.apps/v1/<>",
  "ClusterInfo": {
    "Version": "1.16",
    "Nodes": 0,
    "Pods": 1,
    "Namespaces": 0,
    "Controllers": 1
  },
  "Results": [
    {
      "Name": "<>",
      "Namespace": "default",
      "Kind": "Deployment.apps",
      "Results": {},
      "PodResult": {
        "Name": "",
        "Results": {
          "hostIPCSet": {
            "ID": "hostIPCSet",
            "Message": "Host IPC is not configured",
            "Success": true,
            "Severity": "danger",
            "Category": "Security"
          },
          "hostNetworkSet": {
            "ID": "hostNetworkSet",
            "Message": "Host network is not configured",
            "Success": true,
            "Severity": "warning",
            "Category": "Security"
          },
          "hostPIDSet": {
            "ID": "hostPIDSet",
            "Message": "Host PID is not configured",
            "Success": true,
            "Severity": "danger",
            "Category": "Security"
          }
        },
        "ContainerResults": [
          {
            "Name": "<>",
            "Results": {
              "cpuLimitsMissing": {
                "ID": "cpuLimitsMissing",
                "Message": "CPU limits should be set",
                "Success": false,
                "Severity": "warning",
                "Category": "Efficiency"
              },
              "cpuRequestsMissing": {
                "ID": "cpuRequestsMissing",
                "Message": "CPU requests are set",
                "Success": true,
                "Severity": "warning",
                "Category": "Efficiency"
              },
              "dangerousCapabilities": {
                "ID": "dangerousCapabilities",
                "Message": "Container does not have any dangerous capabilities",
                "Success": true,
                "Severity": "danger",
                "Category": "Security"
              },
              "hostPortSet": {
                "ID": "hostPortSet",
                "Message": "Host port is not configured",
                "Success": true,
                "Severity": "warning",
                "Category": "Security"
              },
              "insecureCapabilities": {
                "ID": "insecureCapabilities",
                "Message": "Container does not have any insecure capabilities",
                "Success": true,
                "Severity": "warning",
                "Category": "Security"
              },
              "livenessProbeMissing": {
                "ID": "livenessProbeMissing",
                "Message": "Liveness probe should be configured",
                "Success": false,
                "Severity": "warning",
                "Category": "Reliability"
              },
              "memoryLimitsMissing": {
                "ID": "memoryLimitsMissing",
                "Message": "Memory limits are set",
                "Success": true,
                "Severity": "warning",
                "Category": "Efficiency"
              },
              "memoryRequestsMissing": {
                "ID": "memoryRequestsMissing",
                "Message": "Memory requests are set",
                "Success": true,
                "Severity": "warning",
                "Category": "Efficiency"
              },
              "notReadOnlyRootFilesystem": {
                "ID": "notReadOnlyRootFilesystem",
                "Message": "Filesystem should be read only",
                "Success": false,
                "Severity": "warning",
                "Category": "Security"
              },
              "privilegeEscalationAllowed": {
                "ID": "privilegeEscalationAllowed",
                "Message": "Privilege escalation not allowed",
                "Success": true,
                "Severity": "danger",
                "Category": "Security"
              },
              "readinessProbeMissing": {
                "ID": "readinessProbeMissing",
                "Message": "Readiness probe should be configured",
                "Success": false,
                "Severity": "warning",
                "Category": "Reliability"
              },
              "runAsPrivileged": {
                "ID": "runAsPrivileged",
                "Message": "Not running as privileged",
                "Success": true,
                "Severity": "danger",
                "Category": "Security"
              },
              "runAsRootAllowed": {
                "ID": "runAsRootAllowed",
                "Message": "Should not be allowed to run as root",
                "Success": false,
                "Severity": "warning",
                "Category": "Security"
              },
              "tagNotSpecified": {
                "ID": "tagNotSpecified",
                "Message": "Image tag is specified",
                "Success": true,
                "Severity": "danger",
                "Category": "Reliability"
              }
            }
          }
        ]
      },
      "CreatedTime": "0001-01-01T00:00:00Z"
    }
  ]

**Comment by danielpacak** [comment]
:wave: @mathieudebrito Thank you for reporting this issue. I assume that the log you are sharing is from a pod controlled by a scan job. Could share the payload of ConfigAuditReport that is created by transforming such log to a custom resource instance?

```
kubectl get configauditreport <name of report> -o yaml
```

One issue that we can fix quickly is making sure that the extension is handling empty reports gracefully, but it's weird why it's empty first of all.

**Comment by mathieudebrito** [comment]
Hi @danielpacak !
Thank you for your quick answer ! 

Here is the result of the `kubectl get configauditreport <name> -o yaml`:
 
>apiVersion: aquasecurity.github.io/v1alpha1
kind: ConfigAuditReport
metadata:
  creationTimestamp: "2021-03-17T22:22:28Z"
  generation: 1
  labels:
    starboard.resource.kind: Deployment
    starboard.resource.name: <name>
    starboard.resource.namespace: default
  name: <name>
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    kind: Deployment
    name: <name>
    uid: 3f200523-52f7-4f92-b070-e08929716c2d
  resourceVersion: "51471617721"
  selfLink: /apis/aquasecurity.github.io/v1alpha1/namespaces/default/configauditreports/<name>
  uid: 9e98353f-9d2f-4274-b144-1b2b34563736
report:
  containerChecks: null
  podChecks: null
  scanner:
    name: ""
    vendor: ""
    version: ""
  summary:
    dangerCount: 0
    passCount: 0
    warningCount: 0
  updateTimestamp: null

**Comment by danielpacak** [comment]
I've seen similar issue when some folks got empty report. Which version of Starboard is it? Are you using CLI or the operator? It looks to me like CRD definitions are not in synch with Go code that's generated. Are you able to uninstall Starboard and install it again with officially release version (v0.9.2)

**Comment by mathieudebrito** [comment]
@danielpacak I've uninstalled everything and reinstalled everything with v0.9.2, same result :(

**Comment by danielpacak** [comment]
@mathieudebrito We've opened a similar issue in the Starboard repo https://github.com/aquasecurity/starboard/issues/449
I think it's related to the first line / clutter in the logs:

```
I0317 23:02:29.566448 1 request.go:621] Throttling request took 1.027018703s, request: GET:https://10.32.0.1:443/apis/admissionregistration.k8s.io/v1beta1?timeout=32s
```

We have to handle it so the JSON is unmarshalled properly.

**Comment by mathieudebrito** [comment]
Hi guys !

Just a quick follow up to tell you that with version 0.10.1, it works back again !

Thank you !

PS: I let you close the issue since I don't know if you want to do action on the lens extension also or not ;)

**Comment by danielpacak** [comment]
Thank you for letting us know @mathieudebrito !
