### ISSUE TITLE
Not compatible with Lens 5

### ISSUE THREAD

**Issue by thpang** [aquasecurity/starboard-lens-extension#52]
Doc says:

![image](https://user-images.githubusercontent.com/32514746/124943956-f028c380-dfda-11eb-9e12-a566eb2afd3c.png)

Lens 5 says:

![image](https://user-images.githubusercontent.com/32514746/124943615-a63fdd80-dfda-11eb-87a0-6ca0cc87a93a.png)

Lens version info:

![image](https://user-images.githubusercontent.com/32514746/124943791-ca032380-dfda-11eb-8429-2ce6a5153b1b.png)

**Comment by danielpacak** [comment]
Unfortunately the Lens Plugins API v5.0 is not compatible with Lens v4.0 :( I will update the readme to Lens >= 4.0 < 5.0
