### ISSUE TITLE
feat: Show color badges for severity on report lists

### ISSUE THREAD

**Issue by nublarsec** [aquasecurity/starboard-lens-extension#83]
It would be much easier to scan the list of report results visually if the counts used the same color badges that are used on details pages. If a count is 0 we can skip the color badge, to make it more obvious where there are findings.

Here's an example I've implemented for the Vulnerability Reports page:
<img width="1329" alt="Screen Shot 2022-04-21 at 1 01 58 PM" src="https://user-images.githubusercontent.com/103554953/164544248-0e3a4900-d8b4-4983-afed-051586c2771a.png">

This works in both the Light and Dark themes, same as the other color badges.

This should be done on the following pages (I believe the others are not implemented yet):

* Vulnerability Reports
* Config Audit Reports
* CIS Kube Bench Reports

**Comment by danielpacak** [comment]
Resolved in #84
